version: '3.3'
services:
  api:
    image: 'yedf/dtm'
    environment:
      IS_DOCKER: '1'
    ports:
      - '36789:36789'
      - '36790:36790'
    volumes:
      - .:/app/work
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ['/app/dtm/main', 'dev']
    working_dir: /app/work
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    ports:
      - '3306:3306'
